flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "launcher_icon/image/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "launcher_icon/image/icon.png"
