name: crelve_paw_harmony_ai
description: Paw Harmony AI
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  app_tracking_transparency: ^2.0.6
  audio_session: ^0.1.18
  badges: ^3.1.2
  cloud_firestore: ^5.0.0
  cloud_functions: ^5.4.0
  collection: ^1.17.1
  connectivity_plus: ^6.0.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^11.2.0
  dio: ^5.4.1
  email_validator: ^3.0.0
  file_picker: ^9.0.1
  firebase_analytics: ^11.0.0
  firebase_app_installations: ^0.3.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.3.4
  firebase_in_app_messaging: ^0.8.0
  firebase_messaging: ^15.0.0
  firebase_performance: ^0.10.0+2
  firebase_remote_config: ^5.2.0
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.0
  flutter_local_notifications: ^18.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  go_router: ^15.2.4
  google_mobile_ads: ^6.0.0
  google_sign_in: ^6.1.6
  hooks_riverpod: ^2.5.1
  http: ^1.3.0
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.0
  intl: ^0.20.1
  json_annotation: ^4.8.1
  just_audio: ^0.10.4
  logger: ^2.5.0
  multi_select_flutter: ^4.1.3
  open_filex: ^4.7.0
  package_info_plus: ^8.1.2
  page_transition: "^2.1.0"
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  platform: ^3.1.4
  purchases_flutter: ^7.0.0
  retrofit: ^4.0.1
  riverpod_annotation: ^2.3.5
  share_plus: ^10.0.0
  shared_preferences: ^2.5.2
  skeleton_text: ^3.0.1
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.2
  supabase_flutter: ^2.8.4
  table_calendar: ^3.2.0
  url_launcher: ^6.3.1
  uuid: ^4.4.2
  version: ^3.0.2
  widgetbook: ^3.5.0
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutterfire_cli: ^1.3.1
  freezed: ^2.4.6
  go_router_builder: ^3.0.1
  json_serializable: ^6.7.1
  pedantic_mono: ^1.29.0
  retrofit_generator: ^9.0.0
  riverpod_analyzer_utils: ^0.4.2
  riverpod_generator: ^2.6.5
  widgetbook_generator: ^3.3.0

dependency_overrides:
  # device_preview 1.2.0 depends on freezed_annotation ^2.4.1
  freezed_annotation: ^2.4.1
  # rotation_log ^0.0.7 requires intl ^0.19.0.
  intl: ^0.19.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/image/
    - assets/web/
    - 7c17ab82-7dd0-43a5-8fd0-d318b7d8f559.wav
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/font/NotoSansJP-Regular.ttf
        - asset: assets/font/NotoSansJP-Bold.ttf
          weight: 700
    - family: VT323
      fonts:
        - asset: assets/fonts/VT323-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true

# make create-native-splashで反映されます
flutter_native_splash:
  color: "FFFFFF"
  image: "assets/image/logoIcon.png"
  color_dark: "FFFFFF"
  image_dark: "assets/image/logoIcon.png"
  fullscreen: true
  android_12:
    icon_background_color: "FFFFFF"
    image: "assets/image/logoIcon.png"
    icon_background_color_dark: "FFFFFF"
    image_dark: "assets/image/logoIcon.png"

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml
